# See https://code.visualstudio.com/Docs/extensions/testing-extensions

os:
  - osx
  - linux

services:
  - xvfb

language: node_js
node_js:
  - node

cache:
  yarn: true

before_script:
  - npm run vscode:prepublish

script:
  - npm test --silent
